service: cloudtrail-logs

provider:
  name: aws
  versionFunctions: false

resources:
  Resources: 
    CloudTrailS3Bucket: 
      Type: AWS::S3::Bucket
      Properties: 
        BucketName:
          Fn::Join:
          - '-'
          -
            - !Ref AWS::AccountId
            - ${self:service}
        LifecycleConfiguration:
          Rules:
            - Id: 
                Fn::Join:
                - '-'
                -
                  - ${self:service}
                  - ${opt:stage}
                  - !Ref AWS::Region
                  - delete-objects-in-1-day
              Status: Enabled
              ExpirationInDays: 1
              NoncurrentVersionExpirationInDays: 1
    BucketPolicy: 
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: !Ref CloudTrailS3Bucket
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Sid: "AWSCloudTrailAclCheck"
              Effect: "Allow"
              Principal: 
                Service: "cloudtrail.amazonaws.com"
              Action: "s3:GetBucketAcl"
              Resource:
                Fn::Join: 
                  - ''
                  - 
                    - 'arn:aws:s3:::'
                    - !Ref CloudTrailS3Bucket
            - 
              Sid: "AWSCloudTrailWrite"
              Effect: "Allow"
              Principal: 
                Service: "cloudtrail.amazonaws.com"
              Action: "s3:PutObject"
              Resource:
                Fn::Join: 
                  - ''
                  - 
                    - 'arn:aws:s3:::'
                    - !Ref CloudTrailS3Bucket
                    - /AWSLogs/
                    - !Ref AWS::AccountId
                    - /*
              Condition: 
                StringEquals:
                  s3:x-amz-acl: "bucket-owner-full-control"
    myTrail: 
      DependsOn: 
        - BucketPolicy
      Type: AWS::CloudTrail::Trail
      Properties: 
        TrailName:
          Fn::Join:
          - '-'
          -
            - ${self:service}
            - ${opt:stage}
            - all
        S3BucketName: !Ref CloudTrailS3Bucket
        IsLogging: true
  Outputs:
    cloudTrailS3Bucket:
      Value: !Ref CloudTrailS3Bucket
      Export:
        # Purposely used hardcoded value for export name. Only one Cloudtrail stack should be setup per account
        Name: cloudTrailS3Bucket